import { getSeedUsers } from './seed-users';
import type { TaskRecord } from './db';
import { defaultEmailNotificationSettings } from './notifications/registry';

export function createEmptyOperationalDb() {
  const users = getSeedUsers();

  return {
    users,
    tasks: [] as TaskRecord[],
    kanbanTasks: [] as import('./kanban').KanbanTaskRecord[],
    transactions: [] as { id: string; userId: string; amount: number; reason: string; timestamp: string }[],
    assets: [] as { id: string; name: string; userId: string | null; user: string | null; status: string }[],
    leaveRequests: [] as { id: string; userId: string; type: string; startDate: string; endDate: string; days: number; reason: string; status: string; createdAt: string }[],
    documents: [] as { id: string; userId: string; name: string; category: string; uploadedAt: string; size: string; storageKey?: string; mimeType?: string }[],
    sessions: [] as { token: string; userId: string; createdAt: string; expiresAt: string; ip?: string; userAgent?: string }[],
    securityAuditLog: [] as { id: string; event: string; userId?: string; actorId?: string; ip?: string; userAgent?: string; detail?: string; createdAt: string }[],
    loginAttemptStates: {} as Record<string, { count: number; windowStart: number; lockedUntil?: number }>,
    authExchangeCodes: [] as { code: string; token: string; expiresAt: string }[],
    notifications: [] as {
      id: string; userId: string; title: string; message: string; read: boolean; createdAt: string;
      triggerId?: string; link?: string; category?: string;
    }[],
    attendanceLogs: [] as { id: string; userId: string; clockIn: string; clockOut: string | null; date: string; earlyClockOutApproved?: boolean }[],
    attendanceRequests: [] as { id: string; userId: string; type: string; date: string; hours?: string; reason?: string; location?: string; time?: string; status: string; createdAt: string }[],
    candidates: [] as { id: string; name: string; role: string; stage: string; email?: string; phone?: string; jobId?: string; notes?: string; interviewDate?: string; source?: string }[],
    jobPostings: [] as { id: string; title: string; department: string; location: string; type: string; status: string; description: string; createdAt: string }[],
    payrollRecords: [] as { id: string; userId: string; period: string; grossPay: number; deductions: number; netPay: number; status: string; breakdown?: Record<string, number> }[],
    salaryStructures: {} as Record<string, { ctc: number; basic: number; hra: number; specialAllowance: number; pfEnabled: boolean; esicEnabled: boolean; ptEnabled: boolean }>,
    reviewCycles: [] as { id: string; name: string; period: string; status: string; startDate: string; endDate: string; template: string; createdAt: string }[],
    offboardingTasks: [] as { id: string; userId: string; title: string; description: string; status: string; dueDate: string; category: string }[],
    policyAcknowledgments: [] as { policyId: string; userId: string; acknowledgedAt: string }[],
    shiftRoster: [] as { id: string; userId: string; date: string; shiftType: string; startTime: string; endTime: string; location: string }[],
    fieldVisits: [] as { id: string; userId: string; userName: string; location: string; lat: number; lng: number; notes: string; createdAt: string }[],
    projects: [] as import('./project-management').ProjectRecord[],
    projectTasks: [] as import('./project-management').ProjectTaskRecord[],
    courses: [] as { id: string; title: string; duration: string; required: boolean; enrolled: string[] }[],
    surveys: [] as { id: string; title: string; description: string; dueIn: string; responses: string[] }[],
    surveyResponses: [] as { id: string; surveyId: string; userId: string; rating: number; feedback: string; createdAt: string }[],
    fieldAgents: [] as { id: string; name: string; location: string; lat: number; lng: number; status: string }[],
    expenses: [] as { id: string; userId: string; title: string; amount: number; status: string; date: string }[],
    tickets: [] as { id: string; title: string; category: string; priority: string; status: string; date: string; userId: string; user: string }[],
    communityPosts: [] as { id: string; userId: string; author: string; type: string; title: string; content: string; likes: number; comments: number; createdAt: string }[],
    events: [] as { id: string; title: string; date: string; time: string; location: string }[],
    polls: [] as { id: string; question: string; options: { label: string; votes: number }[]; voters?: string[] }[],
    chatMessages: [] as { id: string; fromId: string; toId: string; content: string; createdAt: string }[],
    projectMessages: [] as { id: string; projectId: string; fromId: string; authorName: string; content: string; type: 'message' | 'file' | 'meet'; attachmentName?: string; attachmentKey?: string; meetLink?: string; createdAt: string }[],
    aiMessages: {} as Record<string, { id: string; role: 'user' | 'assistant'; content: string; createdAt: string }[]>,
    performanceGoals: [] as { id: string; userId: string; title: string; progress: number; target: number; quarter: string }[],
    performanceReviews: [] as { id: string; userId: string; reviewerId: string; rating: number; feedback: string; period: string; status: string; cycleId?: string; cycleName?: string }[],
    performanceSnapshots: [] as import('./performance-tracking').PerformanceSnapshotRecord[],
    skills: [] as { id: string; userId: string; name: string; level: number; maxLevel: number }[],
    badges: [
      { id: 'b1', name: 'Quality Champion', icon: 'award' },
      { id: 'b2', name: 'Fast Learner', icon: 'trending' },
      { id: 'b3', name: 'Team Player', icon: 'users' },
    ],
    userBadges: [] as { userId: string; badgeId: string }[],
    giftCards: [
      { id: 'gc1', name: 'Amazon Gift Card', pointsCost: 500, value: 500, currency: 'INR' },
      { id: 'gc2', name: 'Flipkart Voucher', pointsCost: 200, value: 200, currency: 'INR' },
    ],
    orgSettings: {
      companyName: 'House of Kaala',
      timezone: 'Asia/Kolkata',
      workWeekStart: 'Monday',
      defaultLeaveDays: 18,
      sickLeaveDays: 12,
      marketplacePenalty: 50,
      fridayScanTime: '18:30',
      notificationsEnabled: true,
      twoFactorRequired: false,
      geoAttendanceRequired: false,
      officeGeofence: { name: 'House of Kaala Office', lat: 12.9716, lng: 77.5946, radiusMeters: 500 },
      emailNotifications: defaultEmailNotificationSettings(),
    },
    emailDigestQueue: [] as { id: string; userId: string; triggerId: string; title: string; message: string; digestType: 'daily' | 'weekly' | 'monthly'; createdAt: string }[],
    emailDigestMeta: {} as { lastDaily?: string; lastWeekly?: string; lastMonthly?: string },
    rolePermissions: {
      employee: { modules: ['dashboard', 'people', 'attendance', 'leave', 'documents', 'assets', 'performance', 'learning', 'surveys', 'community', 'helpdesk', 'marketplace', 'rewards', 'leaderboard', 'chat', 'ai', 'profile', 'notifications', 'expenses', 'timesheets', 'onboarding', 'holidays', 'policies', 'orgchart', 'projects', 'tasks', 'settings', 'security', 'benefits', 'tax'], description: 'Standard employee access' },
      sales: { modules: ['dashboard', 'crm', 'projects', 'tasks', 'field', 'people', 'documents', 'expenses', 'attendance', 'leave', 'timesheets', 'marketplace', 'rewards', 'leaderboard', 'chat', 'ai', 'profile', 'notifications', 'settings', 'security'], description: 'Sales team — CRM, deals, field ops, pipeline, and core HR' },
      executive_assistant: { modules: ['dashboard', 'crm', 'people', 'documents', 'tasks', 'projects', 'field', 'expenses', 'chat', 'ai', 'attendance', 'leave', 'timesheets', 'profile', 'notifications', 'settings', 'security'], description: 'Executive Assistant — CRM, pipeline, and executive support' },
      manager: { modules: ['*'], description: 'Team management and approvals' },
      admin: { modules: ['*'], description: 'Full system access' },
    },
    holidays: [
      { id: 'h1', name: 'Independence Day', date: '2026-08-15', type: 'Public' },
      { id: 'h2', name: 'Diwali', date: '2026-11-01', type: 'Public' },
      { id: 'h3', name: 'Christmas', date: '2026-12-25', type: 'Public' },
      { id: 'h4', name: 'Republic Day', date: '2027-01-26', type: 'Public' },
    ],
    shifts: [] as { id: string; userId: string; shiftType: string; date: string; status: string; reason: string }[],
    policies: [
      { id: 'pol1', title: 'Office Timings', description: 'Core hours: 10:00 AM – 4:00 PM IST. Flexible start between 9:00–10:00 AM with manager approval.', category: 'Attendance', status: 'Active', requiresAck: true },
      { id: 'pol2', title: 'Late Mark Policy', description: 'More than 3 late marks in a month will be reviewed by your manager.', category: 'Attendance', status: 'Active' },
      { id: 'pol3', title: 'Work From Home', description: 'Up to 2 WFH days per week with prior manager approval.', category: 'Remote Work', status: 'Active' },
      { id: 'pol4', title: 'Expense Reimbursement', description: 'Submit expenses within 30 days with valid receipts.', category: 'Finance', status: 'Active' },
      { id: 'pol5', title: 'Code of Conduct', description: 'All employees must follow company values and workplace ethics.', category: 'HR', status: 'Active' },
    ],
    onboardingTasks: [] as { id: string; userId: string; title: string; description: string; status: string; dueDate: string; category: string }[],
    timesheets: [] as { id: string; userId: string; projectId: string; projectName: string; date: string; hours: number; description: string; status: string }[],
    biometricDevices: [] as { id: string; name: string; location: string; status: string; lastSync: string }[],
    courseProgress: {} as Record<string, Record<string, number>>,
    crmLeads: [] as import('./crm').CrmLeadRecord[],
    benefitPlans: [
      { id: 'bp1', name: 'Group Health Insurance', type: 'health', provider: 'Star Health', description: 'Family floater cover ₹5L', employerContribution: 8000, employeeContribution: 2000, status: 'active', enrollmentOpen: true },
      { id: 'bp2', name: 'Term Life Insurance', type: 'life', provider: 'HDFC Life', description: '10× annual CTC coverage', employerContribution: 3000, employeeContribution: 0, status: 'active', enrollmentOpen: true },
      { id: 'bp3', name: 'Provident Fund (EPF)', type: 'pf', provider: 'EPFO', description: 'Mandatory 12% employee + 12% employer', employerContribution: 0, employeeContribution: 0, status: 'active', enrollmentOpen: true, autoEnroll: true },
      { id: 'bp4', name: 'NPS Contribution', type: 'nps', provider: 'NPS Trust', description: 'Additional retirement savings u/s 80CCD(1B)', employerContribution: 0, employeeContribution: 5000, status: 'active', enrollmentOpen: true },
    ] as { id: string; name: string; type: string; provider: string; description: string; employerContribution: number; employeeContribution: number; status: string; enrollmentOpen: boolean; autoEnroll?: boolean }[],
    benefitEnrollments: [] as { id: string; userId: string; planId: string; status: string; enrolledAt: string; dependents: string[] }[],
    signatureRequests: [] as { id: string; documentId: string; documentName: string; userId: string; requestedBy: string; title: string; status: string; createdAt: string; signedAt?: string; signatureData?: string }[],
    investmentDeclarations: [] as import('./tax-compliance').InvestmentDeclaration[],
    form16Records: [] as { id: string; userId: string; financialYear: string; generatedAt: string; data: unknown }[],
    webhooks: [] as { id: string; url: string; events: string[]; secret: string; active: boolean; createdAt: string }[],
    integrations: {
      googleSso: { enabled: false, clientId: '', clientSecret: '', allowedDomain: 'bymarketingonly.com' },
      slack: { enabled: false, webhookUrl: '' },
    },
    dataVersion: 5,
  };
}