/** India payroll calculation — Basic, HRA, PF, ESIC, PT, TDS skeleton. */

export interface SalaryStructure {
  ctc: number;
  basic: number;
  hra: number;
  specialAllowance: number;
  pfEnabled: boolean;
  esicEnabled: boolean;
  ptEnabled: boolean;
}

export interface PayrollBreakdown {
  grossPay: number;
  basic: number;
  hra: number;
  specialAllowance: number;
  pfEmployee: number;
  pfEmployer: number;
  esicEmployee: number;
  esicEmployer: number;
  professionalTax: number;
  tds: number;
  deductions: number;
  netPay: number;
}

const DEFAULT_CTC_BY_ROLE: Record<string, number> = {
  employee: 600000,
  sales: 720000,
  executive_assistant: 840000,
  manager: 1200000,
  admin: 1500000,
};

export function defaultSalaryStructure(role: string): SalaryStructure {
  const ctc = DEFAULT_CTC_BY_ROLE[role] || 600000;
  const monthly = Math.round(ctc / 12);
  const basic = Math.round(monthly * 0.4);
  const hra = Math.round(basic * 0.5);
  const specialAllowance = Math.max(0, monthly - basic - hra);
  return {
    ctc,
    basic,
    hra,
    specialAllowance,
    pfEnabled: true,
    esicEnabled: monthly <= 21000,
    ptEnabled: true,
  };
}

export function computePayroll(structure: SalaryStructure): PayrollBreakdown {
  const grossPay = structure.basic + structure.hra + structure.specialAllowance;

  const pfEmployee = structure.pfEnabled ? Math.round(structure.basic * 0.12) : 0;
  const pfEmployer = structure.pfEnabled ? Math.round(structure.basic * 0.12) : 0;
  const esicEmployee = structure.esicEnabled ? Math.round(grossPay * 0.0075) : 0;
  const esicEmployer = structure.esicEnabled ? Math.round(grossPay * 0.0325) : 0;
  const professionalTax = structure.ptEnabled ? 200 : 0;
  const taxable = grossPay - pfEmployee;
  const tds = Math.round(Math.max(0, taxable - 50000) * 0.05);

  const deductions = pfEmployee + esicEmployee + professionalTax + tds;
  const netPay = grossPay - deductions;

  return {
    grossPay,
    basic: structure.basic,
    hra: structure.hra,
    specialAllowance: structure.specialAllowance,
    pfEmployee,
    pfEmployer,
    esicEmployee,
    esicEmployer,
    professionalTax,
    tds,
    deductions,
    netPay,
  };
}

export function formatINR(n: number) {
  return new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 }).format(n);
}

export function payslipHtml(
  employee: { name: string; email: string; department: string; title?: string },
  period: string,
  breakdown: PayrollBreakdown,
  company: string,
) {
  const rows = [
    ['Basic Salary', breakdown.basic],
    ['HRA', breakdown.hra],
    ['Special Allowance', breakdown.specialAllowance],
    ['Gross Pay', breakdown.grossPay],
    ['PF (Employee)', -breakdown.pfEmployee],
    ['ESIC (Employee)', -breakdown.esicEmployee],
    ['Professional Tax', -breakdown.professionalTax],
    ['TDS', -breakdown.tds],
    ['Net Pay', breakdown.netPay],
  ];
  const tr = rows.map(([label, amt]) =>
    `<tr><td style="padding:8px;border-bottom:1px solid #eee">${label}</td><td style="padding:8px;border-bottom:1px solid #eee;text-align:right;font-weight:${label === 'Net Pay' || label === 'Gross Pay' ? '600' : '400'}">${formatINR(Math.abs(amt as number))}${(amt as number) < 0 ? '' : ''}</td></tr>`,
  ).join('');
  return `<!DOCTYPE html><html><head><meta charset="utf-8"><title>Payslip ${period}</title></head><body style="font-family:system-ui,sans-serif;max-width:640px;margin:40px auto;padding:32px;border:1px solid #ddd;border-radius:12px">
<h1 style="margin:0 0 4px">${company}</h1><p style="color:#666;margin:0 0 24px">Payslip — ${period}</p>
<p><strong>${employee.name}</strong><br>${employee.title || ''} · ${employee.department}<br>${employee.email}</p>
<table style="width:100%;margin-top:24px;border-collapse:collapse">${tr}</table>
<p style="margin-top:32px;font-size:12px;color:#999">Generated by House of Kaala HRMS. Statutory figures are indicative.</p>
</body></html>`;
}